### ISSUE TITLE
Allow provider to return simple boolean values instead of functions

### ISSUE THREAD

**Issue by dguettler** [softlayer/sl-ember-behavior#32]
I found myself in a situation where I would like to have custom behavior for individual providers.
However instead of defining a function I would like to return simple booleans. So the behavior data for an individual provider would look like this:

```
{
  project: true,
  project.edit: false
}
```

Currently I accomplish this by overriding the `isAble` function via an initializer. It would be nice to have this option out-of-the-box.

Changes to the `isAble` function to accomplish this idea:

```
      var behaviors = this.getWithDefault( 'behaviors', null ),
          isAble    = false,
          behaviorGroup,
          providerIsObject,
          providerBehavior;

[...]

      if ( behaviors && behaviors[behaviorGroup] && behaviors[behaviorGroup][behavior] ) {
        providerBehavior = ( providerIsObject  ) ? provider.behaviors[behavior] : true;

        isAble = ('function' === typeof providerBehavior) ? providerBehavior() : providerBehavior;
      }

```

**Comment by notmessenger** [comment]
https://github.com/juwara0 is working on this
