### ISSUE TITLE
Ember.EnumberableUtils.forEach is deprecated, please refactor to use Array.prototype.forEach

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-behavior#47]
May be impacted:
- https://github.com/softlayer/sl-ember-behavior/blob/5a1c26afeee304049aa15f9e4b969751d3d3d95b/tests/dummy/app/routes/application.js#L17
- https://github.com/softlayer/sl-ember-behavior/blob/6d1e09ca7958764efd7591a1807f0819114efe58/README.md#L135

When Ember 1.13 is used by this addon

**Comment by juwara0** [comment]
This issue can be closed. The Ember.EnumberableUtils.forEach method was migrated to Array.prototype.forEach so still works the same. I ran the tests and demo app and did not see a deprecation related to this.
