### ISSUE TITLE
Simplify parameters on sl-able and sl-unable

### ISSUE THREAD

**Issue by jonathandavidson** [softlayer/sl-ember-behavior#53]
There is some unnecessary complexity in the `provider` parameter when an object is supplied. In order to simplify this feature without sacrificing any functionality, the `sl-able` and `sl-unable` components will be revised as follows:
- The `behavior` parameter will be renamed `resource` and will otherwise remain unchanged
- The `provider` parameter will be renamed `activity` and will no longer accept an object, only a string corresponding to the Behavior Group key name used in the Behaviors structure
- An additional `possible` parameter will be added which accepts a boolean, computed property that evaluates to a boolean, or a function returning a boolean. This will take the place of the `behaviors` object passed in through the `provider` parameter since only one behavior (activity) is being evaluated in a component instance.
- The `possible` parameter will be observed to make the component responsive to changes in the value supplied.

**Comment by notmessenger** [comment]
@jonathandavidson For clarification, the `possible` parameter in the 3rd bullet point in the previous comment will accept any input that resolves to a boolean, be it an actual boolean, a computed property or a plain function, correct?

**Comment by jonathandavidson** [comment]
@notmessenger Correct. I have updated the description to reflect that clarification.
