### ISSUE TITLE
Test should assert null

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-behavior#63]
https://github.com/softlayer/sl-ember-behavior/blob/48c612afdb40ec2ee1fd44a76e0db3977fca204b/tests/unit/services/sl-behavior-test.js#L22

https://github.com/softlayer/sl-ember-behavior/blob/48c612afdb40ec2ee1fd44a76e0db3977fca204b/tests/unit/services/sl-behavior-test.js#L130

https://github.com/softlayer/sl-ember-behavior/blob/48c612afdb40ec2ee1fd44a76e0db3977fca204b/tests/unit/services/sl-behavior-test.js#L262

https://github.com/softlayer/sl-ember-behavior/blob/48c612afdb40ec2ee1fd44a76e0db3977fca204b/tests/unit/services/sl-behavior-test.js#L431

https://github.com/softlayer/sl-ember-behavior/blob/48c612afdb40ec2ee1fd44a76e0db3977fca204b/tests/unit/services/sl-behavior-test.js#L538

**Comment by erangeles** [comment]
@notmessenger taking this.
