### ISSUE TITLE
Refactor test(s) that check for parameter types to use assert.throws() call

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-behavior#68]
- Align with the pattern in https://github.com/softlayer/sl-ember-components/blob/develop/tests/unit/components/sl-chart-test.js#L99
- Do not include test for `Symbol`

tests/unit/services/sl-behavior-test.js

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/issues/479 will modify the example to use

**Comment by erangeles** [comment]
@notmessenger taking this.
