### ISSUE TITLE
Does isUnable()'s logic need to be refined?

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-behavior#7]
If the defined behaviors used by the Behavior Service were purely a true/false condition, where each behavior concept in the app is in the list then isUnable() being a pure inverse of a call to isAble() would be fine.

However, since all behaviors do not need to be pre-defined, the absence of one results in a false during a call to isAble().

Given this, is it reasonable that a call to isUnable() would return a true in such a condition, or should it return false in situations where the behavior has not been defined and then be an inverse to the remaining isAble() logic?

**Comment by notmessenger** [comment]
After further review this is indeed the desired behavior.

**Comment by hudlow** [comment]
I believe its current behavior (being the exact inverse of isAble()) is the most conservative approach, and I would support it.
